import js from '@eslint/js';
import jsdoc from 'eslint-plugin-jsdoc';

export default [
  js.configs.recommended, // eslint:recommended
  jsdoc.configs['flat/recommended'], // plugin:jsdoc/recommended
  { // google JavaScript Style Guide v0.14.0, see ./src.js
    rules: {
      'no-cond-assign': 0,
      'no-irregular-whitespace': 2,
      'no-unexpected-multiline': 2,
      'valid-jsdoc': [ 2, [Object] ],
      curly: [ 2, 'multi-line' ],
      'guard-for-in': 2,
      'no-caller': 2,
      'no-extend-native': 2,
      'no-extra-bind': 2,
      'no-invalid-this': 2,
      'no-multi-spaces': 2,
      'no-multi-str': 2,
      'no-new-wrappers': 2,
      'no-throw-literal': 2,
      'no-with': 2,
      'prefer-promise-reject-errors': 2,
      'no-unused-vars': [ 2, [Object] ],
      'array-bracket-newline': 0,
      'array-bracket-spacing': [ 2, 'never' ],
      'array-element-newline': 0,
      'block-spacing': [ 2, 'never' ],
      'brace-style': 2,
      camelcase: [ 2, [Object] ],
      'comma-dangle': [ 2, 'always-multiline' ],
      'comma-spacing': 2,
      'comma-style': 2,
      'computed-property-spacing': 2,
      'eol-last': 2,
      'func-call-spacing': 2,
      indent: [ 2, 2, [Object] ],
      'key-spacing': 2,
      'keyword-spacing': 2,
      'linebreak-style': 2,
      'max-len': [ 2, [Object] ],
      'new-cap': 2,
      'no-array-constructor': 2,
      'no-mixed-spaces-and-tabs': 2,
      'no-multiple-empty-lines': [ 2, [Object] ],
      'no-new-object': 2,
      'no-tabs': 2,
      'no-trailing-spaces': 2,
      'object-curly-spacing': 2,
      'one-var': [ 2, [Object] ],
      'operator-linebreak': [ 2, 'after' ],
      'padded-blocks': [ 2, 'never' ],
      'quote-props': [ 2, 'consistent' ],
      quotes: [ 2, 'single', [Object] ],
      'require-jsdoc': [ 2, [Object] ],
      semi: 2,
      'semi-spacing': 2,
      'space-before-blocks': 2,
      'space-before-function-paren': [ 2, [Object] ],
      'spaced-comment': [ 2, 'always' ],
      'switch-colon-spacing': 2,
      'arrow-parens': [ 2, 'always' ],
      'constructor-super': 2,
      'generator-star-spacing': [ 2, 'after' ],
      'no-new-symbol': 2,
      'no-this-before-super': 2,
      'no-var': 2,
      'prefer-const': [ 2, [Object] ],
      'prefer-rest-params': 2,
      'prefer-spread': 2,
      'rest-spread-spacing': 2,
      'yield-star-spacing': [ 2, 'after' ]
    }
  },
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    rules: {
      'multiline-comment-style': 'error',
    },
  },
]
