export default [
    { // eslint:recommended v8.57.0
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-extra-semi': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-new-symbol': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-octal': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-vars': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error'
    }
  },
  { // plugin:jsdoc/recommended v48.2.0
    rules: {
      'jsdoc/check-access': 'warn',
      'jsdoc/check-alignment': 'warn',
      'jsdoc/check-examples': 'off',
      'jsdoc/check-indentation': 'off',
      'jsdoc/check-line-alignment': 'off',
      'jsdoc/check-param-names': 'warn',
      'jsdoc/check-property-names': 'warn',
      'jsdoc/check-syntax': 'off',
      'jsdoc/check-tag-names': 'warn',
      'jsdoc/check-types': 'warn',
      'jsdoc/check-values': 'warn',
      'jsdoc/empty-tags': 'warn',
      'jsdoc/implements-on-classes': 'warn',
      'jsdoc/imports-as-dependencies': 'off',
      'jsdoc/informative-docs': 'off',
      'jsdoc/match-description': 'off',
      'jsdoc/match-name': 'off',
      'jsdoc/multiline-blocks': 'warn',
      'jsdoc/no-bad-blocks': 'off',
      'jsdoc/no-blank-block-descriptions': 'off',
      'jsdoc/no-blank-blocks': 'off',
      'jsdoc/no-defaults': 'warn',
      'jsdoc/no-missing-syntax': 'off',
      'jsdoc/no-multi-asterisks': 'warn',
      'jsdoc/no-restricted-syntax': 'off',
      'jsdoc/no-types': 'off',
      'jsdoc/no-undefined-types': 'warn',
      'jsdoc/require-asterisk-prefix': 'off',
      'jsdoc/require-description': 'off',
      'jsdoc/require-description-complete-sentence': 'off',
      'jsdoc/require-example': 'off',
      'jsdoc/require-file-overview': 'off',
      'jsdoc/require-hyphen-before-param-description': 'off',
      'jsdoc/require-jsdoc': 'warn',
      'jsdoc/require-param': 'warn',
      'jsdoc/require-param-description': 'warn',
      'jsdoc/require-param-name': 'warn',
      'jsdoc/require-param-type': 'warn',
      'jsdoc/require-property': 'warn',
      'jsdoc/require-property-description': 'warn',
      'jsdoc/require-property-name': 'warn',
      'jsdoc/require-property-type': 'warn',
      'jsdoc/require-returns': 'warn',
      'jsdoc/require-returns-check': 'warn',
      'jsdoc/require-returns-description': 'warn',
      'jsdoc/require-returns-type': 'warn',
      'jsdoc/require-throws': 'off',
      'jsdoc/require-yields': 'warn',
      'jsdoc/require-yields-check': 'warn',
      'jsdoc/sort-tags': 'off',
      'jsdoc/tag-lines': 'warn',
      'jsdoc/text-escaping': 'off',
      'jsdoc/valid-types': 'warn'
    }
  },
  { // google JavaScript Style Guide v0.14.0, see ./src.js
    rules: {
      'no-cond-assign': 0,
      'no-irregular-whitespace': 2,
      'no-unexpected-multiline': 2,
      'valid-jsdoc': [ 2,
        {
          requireParamDescription: false,
          requireReturnDescription: false,
          requireReturn: false,
          prefer: { returns: 'return' }
        }
      ],
      curly: [ 2, 'multi-line' ],
      'guard-for-in': 2,
      'no-caller': 2,
      'no-extend-native': 2,
      'no-extra-bind': 2,
      'no-invalid-this': 2,
      'no-multi-spaces': 2,
      'no-multi-str': 2,
      'no-new-wrappers': 2,
      'no-throw-literal': 2,
      'no-with': 2,
      'prefer-promise-reject-errors': 2,
      'no-unused-vars': [ 2, { args: 'none' } ],
      'array-bracket-newline': 0,
      'array-bracket-spacing': [ 2, 'never' ],
      'array-element-newline': 0,
      'block-spacing': [ 2, 'never' ],
      'brace-style': 2,
      camelcase: [ 2, { properties: 'never' } ],
      'comma-dangle': [ 2, 'always-multiline' ],
      'comma-spacing': 2,
      'comma-style': 2,
      'computed-property-spacing': 2,
      'eol-last': 2,
      'func-call-spacing': 2,
      indent: [
        2,
        2,
        {
          CallExpression: { arguments: 2 },
          FunctionDeclaration: { body: 1, parameters: 2 },
          FunctionExpression: { body: 1, parameters: 2 },
          MemberExpression: 2,
          ObjectExpression: 1,
          SwitchCase: 1,
          ignoredNodes: [ 'ConditionalExpression' ]
        }
      ],
      'key-spacing': 2,
      'keyword-spacing': 2,
      'linebreak-style': 2,
      'max-len': [
        2,
        {
          code: 80,
          tabWidth: 2,
          ignoreUrls: true,
          ignorePattern: 'goog.(module|require)'
        }
      ],
      'new-cap': 2,
      'no-array-constructor': 2,
      'no-mixed-spaces-and-tabs': 2,
      'no-multiple-empty-lines': [ 2, { max: 2 } ],
      'no-new-object': 2,
      'no-tabs': 2,
      'no-trailing-spaces': 2,
      'object-curly-spacing': 2,
      'one-var': [ 2, { var: 'never', let: 'never', const: 'never' } ],
      'operator-linebreak': [ 2, 'after' ],
      'padded-blocks': [ 2, 'never' ],
      'quote-props': [ 2, 'consistent' ],
      quotes: [ 2, 'single', { allowTemplateLiterals: true } ],
      'require-jsdoc': [
        2,
        {
          require: {
            FunctionDeclaration: true,
            MethodDefinition: true,
            ClassDeclaration: true
          }
        }
      ],
      semi: 2,
      'semi-spacing': 2,
      'space-before-blocks': 2,
      'space-before-function-paren': [
        2,
        {
          asyncArrow: 'always',
          anonymous: 'never',
          named: 'never'
        }
      ],
      'spaced-comment': [ 2, 'always' ],
      'switch-colon-spacing': 2,
      'arrow-parens': [ 2, 'always' ],
      'constructor-super': 2,
      'generator-star-spacing': [ 2, 'after' ],
      'no-new-symbol': 2,
      'no-this-before-super': 2,
      'no-var': 2,
      'prefer-const': [ 2, { destructuring: 'all' } ],
      'prefer-rest-params': 2,
      'prefer-spread': 2,
      'rest-spread-spacing': 2,
      'yield-star-spacing': [ 2, 'after' ]
    }
  },
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    rules: {
      'multiline-comment-style': 'error',
    },
  },
]
